SD FPT review (mandatory)
DSC-iTC/cPP pull request #281
Opened 2024-04-25 12:59 UTC by woodbe

Some testing updates for the FPT EAs

2024-05-07 13:52 UTC, slpotte approved these changes
All looks good to me.

2024-05-07 15:37 UTC, jvdsn requested changes

2024-05-07 15:37 UTC, jvdsn commented on SD_DSC.adoc
> +
"evalautor" typo
Also, following other tests, maybe we should write `Test 3 [conditional]:`? I know there's an open issue regarding the consistency for Milestone v3.0.

2024-05-08 12:57 UTC, jvdsn approved these changes

2024-05-08 13:07 UTC, merged