edit FCS_RBG_EXT to FCS_RBG
DSC-iTC/cPP pull request #316
Opened 2024-07-01 20:11 UTC by woodbe

cPP change for only remaining location.

SD will take a little more review since EAs have not been updated yet.

This is to close #260.

2024-07-01 22:08 UTC, jvdsn commented
Is this something the crypto catalog needs to review?

2024-07-02 10:30 UTC, woodbe commented
No, this is us just needing to clean up the move from the EXT to the CC:2022. But it isn't done yet either.

2024-07-24 15:12 UTC, woodbe commented
I have made all the updates I was planning, this is ready for review now (hence the assignment of reviewers)

2024-07-24 18:44 UTC, jvdsn requested changes

2024-07-24 18:44 UTC, jvdsn commented on SD_DSC.adoc
> +The evaluator shall develop and execute or verify and observe the developer tooling which selects the seed source and provides it to the DRBG. The evaluator shall verify that the request succeeds.
"provides it" -> "provides its output"?

2024-07-24 19:06 UTC, woodbe commented on SD_DSC.adoc
> +The evaluator shall develop and execute or verify and observe the developer tooling which selects the seed source and provides it to the DRBG. The evaluator shall verify that the request succeeds.
edited

2024-07-24 19:59 UTC, jvdsn approved these changes

2024-07-25 14:17 UTC, slpotte approved these changes

2024-08-02 16:06 UTC, merged